### ISSUE TITLE
Etap 1- CheckList

### ISSUE THREAD

**Issue by pjaworski287** [marekzarychta/tpw_mz_pj#4]
Etap 1-CheckList
- [X] text is in C#
- [X] build succeeded
- [X] all UT are green
- [X] `Data` layer is clearly stated using language terms only (no database, no file)
- [X] `Data` API is clearly stated
- [X] `Data` API is abstract
- [X] `Logic` layer is clearly stated using language terms only
- [X] `Logic` API is clearly stated
- [X] `Logic` uses only the abstract `Data` layer API
- [X] `Presentation` layer is clearly stated using language terms only
- [X] `Presentation` uses only the abstract `Logic` layer API
- [X] MVVM and XAMLare applied to implement GUI
- [X] reactive and interactive user interaction for user (operator) communication
- [X] reactive and interactive programming is used for the communication of layers 
- [X] `Presentation` - object model representing process data
- [X] Fulfill functional requirements of the task
- [X] Unit Test - layers are tested independently using abstract API
- [X] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purposes (expected but not required)
